### ISSUE TITLE
For Variable MnM product, the Shipping option "Packed separately" doesn't save

### ISSUE THREAD

**Issue by limist** [Backcourt/wc-mnm-variable#59]
@helgatheviking Hi, we're seeing that with a Variable MnM product (that is also a subscription product), selecting the Shipping option of "Packed separately" doesn't get saved.

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/4e7a9959-3b72-40d1-8819-b0fdecd658d9">

...i.e. we select the middle option of "Packed separately" per above, and then click the product's Update (save) button as usual.  But then after the update/save is done and the page reloads, when we scroll down and view the Shipping options, it reverts back to the default "Packed together" per below:

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/a7ffd0be-e543-412e-aad7-d3af83660a73">

Noting too that the "Packed separately" option saves and behaves as expected for regular (non-variable) MnM products. 

Thanks in advance for your help on this!  🙏

**Comment by limist** [comment]
@helgatheviking Oh, one more key detail, sorry: It seems that even though the display of the Shipping option is stuck on "Packed together", we're seeing that with test orders sent through to ShipStation, those test orders do have the usual and expected distinct/separate line-items for each item in the MnM Variable product — thus showing behavior as if the "Packed separately" option was active. 

So it could be that the "Packed separately" option is in fact saved, but there's something missing/off with the display logic for the Shipping options.  Thanks!

**Comment by helgatheviking** [comment]
>So it could be that the "Packed separately" option is in fact saved, but there's something missing/off with the display logic for the Shipping options. Thanks!

I think it's this. The core MNM plugin displays the shipping options based on a global custom product variable and in vmnn it's a different global.
